services:
  reverse_proxy:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/ssl

    networks:
      - frontend
      - backend
  app:
    image: nginx:alpine
    volumes:
      - ./app:/usr/share/nginx/html
    networks:
      - backend

  app1:
    image: nginx:alpine
    volumes:
      - ./app1:/usr/share/nginx/html
    networks:
      - backend

  app2:
    image: nginx:alpine
    volumes:
      - ./app2:/usr/share/nginx/html
    networks:
      - backend

  app3:
    image: nginx:alpine
    volumes:
      - ./app3:/usr/share/nginx/html
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
